export const METHODS = {
  // Getting Updates
  getting_updates: [
    "getUpdates",
    "setWebhook",
    "deleteWebhook",
    "getWebhookInfo",
  ],
  // Setup
  setup: [
    "getMe",
    "logOut",
    "close",
  ],
  // Messages
  messages: [
    "sendMessage",
    "forwardMessage",
    "copyMessage",
    "sendPhoto",
    "sendAudio",
    "sendDocument",
    "sendVideo",
    "sendAnimation",
    "sendVoice",
    "sendVideoNote",
    "sendMediaGroup",
    "sendLocation",
    "editMessageLiveLocation",
    "stopMessageLiveLocation",
    "sendVenue",
    "sendContact",
    "sendPoll",
    "sendDice",
    "sendChatAction",
    "getUserProfilePhotos",
    "getFile",
    "answerCallbackQuery",
  ],
  // Chat Management
  chat_management: [
    "kickChatMember",
    "banChatMember",
    "unbanChatMember",
    "restrictChatMember",
    "promoteChatMember",
    "setChatAdministratorCustomTitle",
    "banChatSenderChat",
    "unbanChatSenderChat",
    "setChatPermissions",
    "exportChatInviteLink",
    "createChatInviteLink",
    "editChatInviteLink",
    "revokeChatInviteLink",
    "approveChatJoinRequest",
    "declineChatJoinRequest",
    "setChatPhoto",
    "deleteChatPhoto",
    "setChatTitle",
    "setChatDescription",
    "pinChatMessage",
    "unpinChatMessage",
    "unpinAllChatMessages",
    "leaveChat",
    "getChat",
    "getChatAdministrators",
    "getChatMembersCount",
    "getChatMemberCount",
    "getChatMember",
    "setChatStickerSet",
    "deleteChatStickerSet",
  ],
  /** Forum Management */
  forum_management: [
    "getForumTopicIconStickers",
    "createForumTopic",
    "editForumTopic",
    "closeForumTopic",
    "reopenForumTopic",
    "deleteForumTopic",
    "unpinAllForumTopicMessages",
    "editGeneralForumTopic",
    "closeGeneralForumTopic",
    "reopenGeneralForumTopic",
    "hideGeneralForumTopic",
    "unhideGeneralForumTopic",
  ],
  /** Bot Settings */
  bot_settings: [
    "setMyCommands",
    "deleteMyCommands",
    "getMyCommands",
    "setChatMenuButton",
    "getChatMenuButton",
    "setMyDescription",
    "getMyDescription",
    "setMyShortDescription",
    "getMyShortDescription",
    "setMyDefaultAdministratorRights",
    "getMyDefaultAdministratorRights",
  ],
  // Updating Messages
  updating_messages: [
    "editMessageText",
    "editMessageCaption",
    "editMessageMedia",
    "editMessageReplyMarkup",
    "stopPoll",
    "deleteMessage",
  ],
  // Stickers
  stickers: [
    "sendSticker",
    "getStickerSet",
    "getCustomEmojiStickers",
    "uploadStickerFile",
    "createNewStickerSet",
    "addStickerToSet",
    "setStickerPositionInSet",
    "deleteStickerFromSet",
    "setStickerEmojiList",
    "setStickerKeywords",
    "setStickerMaskPosition",
    "setStickerSetTitle",
    "deleteStickerSet",
    "setStickerSetThumbnail",
    "setCustomEmojiStickerSetThumbnail",
  ],
  // Inline Mode
  inline_mode: [
    "answerInlineQuery",
    "answerWebAppQuery",
  ],
  // Payments
  payments: [
    "sendInvoice",
    "createInvoiceLink",
    "answerShippingQuery",
    "answerPreCheckoutQuery",
  ],
  // Telegram Passport
  telegram_passport: [
    "setPassportDataErrors",
  ],
  // Games
  games: [
    "sendGame",
    "setGameScore",
    "getGameHighScores",
  ],
} as const;
